openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for focus
paths:
    /focus/tasks:
        get:
            tags:
                - task
            summary: list task
            description: List all tasks.
            operationId: task#list
            parameters:
                - name: parent_id
                  in: query
                  description: The ID of the parent task
                  allowEmptyValue: true
                  schema:
                    type: string
                    description: The ID of the parent task
                    example: Repudiandae praesentium consectetur dolorem non.
                  example: Minus aut repudiandae quis itaque quam maiores.
                - name: recursive
                  in: query
                  description: Whether to include all subtasks recursively
                  allowEmptyValue: true
                  schema:
                    type: boolean
                    description: Whether to include all subtasks recursively
                    example: false
                  example: false
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TaskdetailCollection'
                            example:
                                - actual_time: 1563727322442016446
                                  completed_at: 3961315908280103348
                                  created_at: 1693411996920393395
                                  estimated_time: 2205035097241353242
                                  id: Eligendi non incidunt quis quae.
                                  is_leaf: true
                                  lead_time: 4048349936130991076
                                  parent_id: Modi architecto rerum.
                                  started_at: 1079979941143135681
                                  status: Quae omnis.
                                  title: Omnis commodi perspiciatis.
                                - actual_time: 1563727322442016446
                                  completed_at: 3961315908280103348
                                  created_at: 1693411996920393395
                                  estimated_time: 2205035097241353242
                                  id: Eligendi non incidunt quis quae.
                                  is_leaf: true
                                  lead_time: 4048349936130991076
                                  parent_id: Modi architecto rerum.
                                  started_at: 1079979941143135681
                                  status: Quae omnis.
                                  title: Omnis commodi perspiciatis.
                                - actual_time: 1563727322442016446
                                  completed_at: 3961315908280103348
                                  created_at: 1693411996920393395
                                  estimated_time: 2205035097241353242
                                  id: Eligendi non incidunt quis quae.
                                  is_leaf: true
                                  lead_time: 4048349936130991076
                                  parent_id: Modi architecto rerum.
                                  started_at: 1079979941143135681
                                  status: Quae omnis.
                                  title: Omnis commodi perspiciatis.
                                - actual_time: 1563727322442016446
                                  completed_at: 3961315908280103348
                                  created_at: 1693411996920393395
                                  estimated_time: 2205035097241353242
                                  id: Eligendi non incidunt quis quae.
                                  is_leaf: true
                                  lead_time: 4048349936130991076
                                  parent_id: Modi architecto rerum.
                                  started_at: 1079979941143135681
                                  status: Quae omnis.
                                  title: Omnis commodi perspiciatis.
                "401":
                    description: 'Unauthorized: Unauthorized'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'InternalServerError: Internal server error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - task
            summary: create task
            description: Create a new task.
            operationId: task#create
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateTaskInput2'
                        example:
                            parent_id: Ullam dolor sint odio aut enim saepe.
                            title: Vel error odio corporis animi praesentium quasi.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Createtaskoutput'
                            example:
                                created_at: 4115134583085920421
                                id: Quisquam aut omnis laborum eligendi repudiandae ratione.
                "401":
                    description: 'Unauthorized: Unauthorized'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'InternalServerError: Internal server error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /focus/tasks/{task_id}:
        delete:
            tags:
                - task
            summary: delete task
            description: Delete a task.
            operationId: task#delete
            parameters:
                - name: task_id
                  in: path
                  description: The ID of the task
                  required: true
                  schema:
                    type: string
                    description: The ID of the task
                    example: Perspiciatis illum sunt quo.
                  example: Qui magnam autem mollitia ut quia harum.
            responses:
                "204":
                    description: No Content response.
                "401":
                    description: 'Unauthorized: Unauthorized'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'TaskNotFound: Task not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'InternalServerError: Internal server error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        patch:
            tags:
                - task
            summary: update task
            description: Update a task.
            operationId: task#update
            parameters:
                - name: task_id
                  in: path
                  description: The ID of the task
                  required: true
                  schema:
                    type: string
                    description: The ID of the task
                    example: Et et vitae natus.
                  example: Earum doloremque laborum excepturi porro omnis eos.
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TaskUpdateInput2'
                        example:
                            estimated_time: 7275710883003218401
                            next_id: Quisquam necessitatibus earum dolores occaecati labore qui.
                            parent_id: Reiciendis dolorum est qui ratione consequatur quis.
                            status: Error eos ea ut.
                            title: Assumenda assumenda dolores culpa dolore.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Taskdetail'
                            example:
                                actual_time: 6683983230654943632
                                completed_at: 5231580089122856446
                                created_at: 6005120341942138880
                                estimated_time: 3293655805994328534
                                id: Non corrupti.
                                is_leaf: false
                                lead_time: 268725083743420188
                                parent_id: Voluptatem nisi.
                                started_at: 2918745311858220326
                                status: Voluptatibus magni facilis beatae cumque placeat.
                                title: Fugiat qui ut a officia.
                "401":
                    description: 'Unauthorized: Unauthorized'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'TaskNotFound: Task not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "500":
                    description: 'InternalServerError: Internal server error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        CreateTaskInput:
            type: object
            properties:
                authorization:
                    type: string
                    description: The authorization header
                    example: Voluptas nihil.
                parent_id:
                    type: string
                    description: The parent ID of the task
                    example: Iusto non ullam rerum.
                title:
                    type: string
                    description: The title of the task
                    example: Alias ea excepturi voluptatem.
            example:
                authorization: Voluptatem dolores quae excepturi.
                parent_id: Assumenda ratione quos quas.
                title: Harum enim soluta labore et.
            required:
                - authorization
                - title
        CreateTaskInput2:
            type: object
            properties:
                parent_id:
                    type: string
                    description: The parent ID of the task
                    example: Architecto omnis suscipit magni aliquam consequatur laborum.
                title:
                    type: string
                    description: The title of the task
                    example: In voluptatibus et.
            example:
                parent_id: Minima voluptatem consequatur.
                title: Provident pariatur dolor alias.
            required:
                - title
        Createtaskoutput:
            type: object
            properties:
                created_at:
                    type: integer
                    description: The timestamp when the task was created
                    example: 598169950812855446
                    format: int64
                id:
                    type: string
                    description: The ID of the task
                    example: Accusamus in ut corporis dolorem.
            example:
                created_at: 5026725195044610386
                id: Necessitatibus in.
            required:
                - id
                - created_at
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            description: Unauthorized
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        TaskDeleteInput:
            type: object
            properties:
                authorization:
                    type: string
                    description: The authorization header
                    example: Facilis exercitationem itaque autem dolores deserunt sint.
                task_id:
                    type: string
                    description: The ID of the task
                    example: Nihil blanditiis ut eligendi possimus facilis sed.
            example:
                authorization: In quam.
                task_id: Iste provident cumque dolor.
            required:
                - authorization
                - task_id
        TaskUpdateInput:
            type: object
            properties:
                authorization:
                    type: string
                    description: The authorization header
                    example: Velit autem error.
                estimated_time:
                    type: integer
                    description: The estimated time of the task
                    example: 8209120019216364190
                    format: int64
                next_id:
                    type: string
                    description: The next ID of the task
                    example: Ullam laborum quibusdam fugiat optio cum autem.
                parent_id:
                    type: string
                    description: The parent ID of the task
                    example: Nihil deleniti aperiam enim explicabo assumenda.
                status:
                    type: string
                    description: The status of the task
                    example: Quidem odit quisquam.
                task_id:
                    type: string
                    description: The ID of the task
                    example: Dolores ratione et id ipsum.
                title:
                    type: string
                    description: The title of the task
                    example: Sit aliquid facere est quidem ex et.
            example:
                authorization: Officia commodi consequuntur.
                estimated_time: 5566909707384005942
                next_id: Earum at ullam nostrum ratione dolor ab.
                parent_id: Numquam molestiae officia quasi neque fugiat aut.
                status: Incidunt architecto cum et quas tempore.
                task_id: Perferendis corporis expedita ut dolor rerum qui.
                title: Dignissimos error perferendis molestiae.
            required:
                - authorization
                - task_id
        TaskUpdateInput2:
            type: object
            properties:
                estimated_time:
                    type: integer
                    description: The estimated time of the task
                    example: 710880585158450281
                    format: int64
                next_id:
                    type: string
                    description: The next ID of the task
                    example: Libero sint debitis hic recusandae.
                parent_id:
                    type: string
                    description: The parent ID of the task
                    example: Aperiam illum dolore omnis.
                status:
                    type: string
                    description: The status of the task
                    example: Sequi delectus sapiente architecto repudiandae.
                title:
                    type: string
                    description: The title of the task
                    example: Illum rerum ab et enim nostrum ipsam.
            example:
                estimated_time: 4099388843415813766
                next_id: Libero ab fuga eius voluptatem.
                parent_id: Quis aut labore.
                status: Autem eaque earum molestiae culpa explicabo.
                title: Aut ut fugit accusantium.
        Taskdetail:
            type: object
            properties:
                actual_time:
                    type: integer
                    description: The actual time of the task
                    example: 5249552095043595204
                    format: int64
                completed_at:
                    type: integer
                    description: The timestamp when the task was completed
                    example: 2197246153755987613
                    format: int64
                created_at:
                    type: integer
                    description: The timestamp when the task was created
                    example: 9181711262828295258
                    format: int64
                estimated_time:
                    type: integer
                    description: The estimated time of the task
                    example: 5985361373308165509
                    format: int64
                id:
                    type: string
                    description: The ID of the task
                    example: Dolores quo quidem sit perferendis cum modi.
                is_leaf:
                    type: boolean
                    description: Whether the task is a leaf task
                    example: true
                lead_time:
                    type: integer
                    description: The lead time of the task
                    example: 4674978404072781382
                    format: int64
                parent_id:
                    type: string
                    description: The parent ID of the task
                    example: Aliquam dolorem possimus ut vitae.
                started_at:
                    type: integer
                    description: The timestamp when the task was started
                    example: 555245579651135686
                    format: int64
                status:
                    type: string
                    description: The status of the task
                    example: Magni reiciendis molestiae illum est et et.
                title:
                    type: string
                    description: The title of the task
                    example: Itaque magni.
            example:
                actual_time: 2170657563723395353
                completed_at: 8535817410945943115
                created_at: 6087193715872304477
                estimated_time: 6149701451747387786
                id: Voluptatem aliquam et sit pariatur atque.
                is_leaf: false
                lead_time: 4029912259605724373
                parent_id: Eius ut incidunt.
                started_at: 3458969123558735118
                status: Atque enim inventore.
                title: Recusandae vitae asperiores accusamus et.
            required:
                - id
                - title
                - created_at
                - status
        TaskdetailCollection:
            type: array
            items:
                $ref: '#/components/schemas/Taskdetail'
            example:
                - actual_time: 1563727322442016446
                  completed_at: 3961315908280103348
                  created_at: 1693411996920393395
                  estimated_time: 2205035097241353242
                  id: Eligendi non incidunt quis quae.
                  is_leaf: true
                  lead_time: 4048349936130991076
                  parent_id: Modi architecto rerum.
                  started_at: 1079979941143135681
                  status: Quae omnis.
                  title: Omnis commodi perspiciatis.
                - actual_time: 1563727322442016446
                  completed_at: 3961315908280103348
                  created_at: 1693411996920393395
                  estimated_time: 2205035097241353242
                  id: Eligendi non incidunt quis quae.
                  is_leaf: true
                  lead_time: 4048349936130991076
                  parent_id: Modi architecto rerum.
                  started_at: 1079979941143135681
                  status: Quae omnis.
                  title: Omnis commodi perspiciatis.
                - actual_time: 1563727322442016446
                  completed_at: 3961315908280103348
                  created_at: 1693411996920393395
                  estimated_time: 2205035097241353242
                  id: Eligendi non incidunt quis quae.
                  is_leaf: true
                  lead_time: 4048349936130991076
                  parent_id: Modi architecto rerum.
                  started_at: 1079979941143135681
                  status: Quae omnis.
                  title: Omnis commodi perspiciatis.
                - actual_time: 1563727322442016446
                  completed_at: 3961315908280103348
                  created_at: 1693411996920393395
                  estimated_time: 2205035097241353242
                  id: Eligendi non incidunt quis quae.
                  is_leaf: true
                  lead_time: 4048349936130991076
                  parent_id: Modi architecto rerum.
                  started_at: 1079979941143135681
                  status: Quae omnis.
                  title: Omnis commodi perspiciatis.
tags:
    - name: task
